// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cowcbkdmwcwblcpgxsgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvd2Nia2Rtd2N3YmxjcGd4c2dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTMwMzEsImV4cCI6MjA3NDcyOTAzMX0._jmyWVpvFE07YFb9xlgOle9f038i8RxZOEpcc_o6YSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});